SRC += muse.c

MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
# AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
DIP_SWITCH_ENABLE = no

# Steno
STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
